name: Executing custom action in bash
on:
  push:
    branches:
      - main
jobs:
  checking_custom_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checking code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Executing Custom Bash Action
        uses: pgmfernandes/custom-bash-action@main
      - name: Get Pokemon name
        uses: philschmid/blog-custom-github-action@master # or @release_version (e.g. v1)
        id: pokemon
        with:
          pokemon_id: 150
